name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Run `cargo fmt` to check formatting
      - name: Check code formatting
        run: cargo fmt --all -- --check

      # Run `cargo clippy` for linting
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # Run tests
      - name: Run tests
        run: cargo test --all-features
